### ISSUE TITLE
Searching on Playlist view makes all songs disappear forever.

### ISSUE THREAD

**Issue by oxplot** [quodlibet/quodlibet#1761]
Steps to reproduce:

 1. Change to Playlist view (View menu -> Playlists)
 2. Enter a search term
 3. Clear the search term

Expected result: see all songs

Actual result: No songs

No amount of reload/refresh library fixes this. Reverting back to default view does not fix it either.

**Comment by declension** [comment]
Thanks for the report. 

Confirmed on git `master` (rev ca53d77b27d11be5daa750603e32b1349c455540)

**Comment by declension** [comment]
Note this is almost certainly a by-product of not selecting a playlist yet maintaining the Songlist on change of Browser.

(current workaround: click on a playlist)

**Comment by weyfonk** [comment]
Hi, I've just submitted a PR that should fix this particular issue. 
Still, the search feature doesn't seem to work well when no playlist is selected (independently from that PR). 
What kind of behaviour should we be expecting here? Should the search filter all songs, or only the ones that are in at least one playlist?

**Comment by lazka** [comment]
I think we should just remember the playlist selection and restore it in the playlist browser.

**Comment by fecraow** [comment]
@lazka that would be an improvement, but it still doesn't account for the first time someone goes to the playlist browser, or if there's no playlists (or last selected playlist was deleted). maybe it would be best to select the last playlist, if possible, but fall back to simply clearing the song list?
