### ISSUE TITLE
waveformseekbar: ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by lazka** [quodlibet/quodlibet#2387]
https://sentry.io/share/issue/3134323431352e323735363939363437/

How: Quickly disable/enable the waveform seekbar plugin multiple times.

@ptitjes 

I guess it's hard to hit, so not that urgent

**Comment by ptitjes** [comment]
The sentry report is nice ! :)
I'll have a look into it this week end.

**Comment by ptitjes** [comment]
@lazka I can't reproduce it here... so I would need some more input from you.

If there is a division by zero, this means that `width * pixel_ratio = 1`. So if you are in HiDPI mode that would mean that `width = .5px`, and otherwise that would mean that `width = 1px`.

Should I do a blind fix and just test for `width * pixel_ratio` being 1 ?

**Comment by ptitjes** [comment]
I could also test for the visibility of the component, but as I can't reproduce it, I won't know if that fixes the problem.

**Comment by urielz** [comment]
I can reproduce it. It took me 5 seconds of checking/unchecking the waveform seek bar plugin quickly to get the crash. Did you try that @ptitjes? 

It seems your suggestion of testing when width * pixel_ratio = 1 should work... this is the error I got:

**Traceback (most recent call last):**

**.../quodlibet/ext/events/waveformseekbar.py", line 122, in _on_bus_message
    self._update_redraw_interval()**

**.../quodlibet/ext/events/waveformseekbar.py", line 138, in _update_redraw_interval
    interval = self._waveform_scale.compute_redraw_interval()**

 **.../quodlibet/ext/events/waveformseekbar.py", line 256, in compute_redraw_interval
    return length * 1000 / (width * pixel_ratio - 1)**

**ZeroDivisionError: float division by zero**

**Comment by lazka** [comment]
![screenshot from 2017-05-20 07-02-17](https://cloud.githubusercontent.com/assets/991986/26273166/7308a3ae-3d2a-11e7-8f5e-e8e63bac3d1e.png)

No HiDPI, maybe that's the difference.

**Comment by ptitjes** [comment]
I see ! So I planted a `if width * pixel_ratio - 1 == 1: print("Crash")` in my `compute_redraw_interval` code and I can indeed trigger it when enabling/disabling quickly.

So I have a fix for this enabling/disabling quickly, which is to correctly cancel the pipeline in the destroy method:
```
     def _on_destroy(self, *args):
+        if self._pipeline:
+            self._pipeline.set_state(Gst.State.NULL)
+            self._clean_pipeline()
         self._label_tracker.destroy()
         self._redraw_tracker.destroy()
```

I think that correctly cancelling the pipeline is good practice anyway so I'll add a commit just for that in my PR. However, here, the "Crash" is also triggered at startup, as the seekbar component is not yet visible but the waveform computation has finished. Do you have that too ? (or my laptop is too fast ;p)

**Comment by ptitjes** [comment]
The two commits in #2392 should fix the issue.

**Comment by lazka** [comment]
Still a problem it seems (assuming I correctly applied the fixes on quodlibet-3.9): https://sentry.io/share/issue/3134323431352e323735363939363437/

**Comment by ptitjes** [comment]
@lazka Is this also happening by quickly enabling/disabling multiple times ? Also can you tell me what length your currently playing song has (as this changes the time needed to process the waveform) ?

**Comment by lazka** [comment]
That's a user submitted report, so I don't know. The song length is "158.29333333333332". I'll have a look later.

**Comment by lazka** [comment]
What's the reason for the "-1" in compute_redraw_interval() and draw_waveform() ?

**Comment by ptitjes** [comment]
@lazka The reason for using `width * pixel_ratio - 1` in `draw_waveform()` is that with Cairo you have to draw in the middle of pixels [1], else everything is blurry. Then, in `compute_redraw_interval()`, this is just to align the redraws to the pixel count that have to be drawn.

I guess the question is more why does the component has a width of 1 ?

[1] https://www.cairographics.org/FAQ/#sharp_lines

**Comment by lazka** [comment]
Why does drawing in the middle of pixels change the amount of pixels being drawn?

**Comment by ptitjes** [comment]
Well, thinking of it now, it indeed seems dumb. I was thinking of inclusive intervals whereas the allocated width is a right-open interval. I think you can remove both `- 1`...

**Comment by lazka** [comment]
done, thanks

**Comment by ptitjes** [comment]
Thank you @lazka !
