### ISSUE TITLE
App icon is incorrect under KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [quodlibet/quodlibet#2974]
Hi
I have Quod libet 4.1.0 on Arch Linux running KDE Plasma Wayland session.
Window decoration show the Wayland generic icon instead Quod libet icon.

![quod libet](https://user-images.githubusercontent.com/15967631/45727488-56c66380-bb9a-11e8-9c9c-cb6cfa4e9c04.png)

**Comment by frestr** [comment]
This was probably fixed in 36ef24bb56bd0b3b301a912b2bc696398313bff6. I guess you can either install quodlibet-git from AUR or apply the fix described in #2889 to see if it helps.

**Comment by glaubersm** [comment]
Hi frestr
I have just installed quodlibet-git. Bug persists.

**Comment by frestr** [comment]
The old desktop file might still be installed. Could you verify that the installed desktop file contains the line `StartupWMClass=quodlibet`, with a lowercase q?

**Comment by glaubersm** [comment]
I have two desktop files:
~/.local/share/applications/io.github.quodlibet.QuodLibet.desktop
/usr/share/applications/io.github.quodlibet.QuodLibet.desktop

First desktop file had uppercase Q. I changed to q, restarted my session but the icon is still incorrect. Second desktop file already had lowercase q.

**Comment by frestr** [comment]
Ok, thanks for checking. Seems to be a separate bug then.

**Comment by lazka** [comment]
I remember some post on planet-gnome that the full app id needs to be passed to GLib.set_prgname which we don't do currently.

**Comment by lazka** [comment]
Might be fixed in master

**Comment by lazka** [comment]
I've tested with KDE and it works now.

**Comment by glaubersm** [comment]
Thank you very much for the quick fix.
Have a nice day.
