### ISSUE TITLE
Ex Falso: Preference interface doesn't open (TypeError)

### ISSUE THREAD

**Issue by CreamyCookie** [quodlibet/quodlibet#3644]
Steps to reproduce
------------------
1. Click on bottom left cog icon.
2. Click on "Preferences"

Expected Output
---------------
a preference interface

Actual Output
-------------
```pytb
TypeError: __init__() missing 1 required positional argument: 'parent'
------
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/quodlibet/qltk/exfalsowindow.py", line 75, in prefs_cb
    window = PreferencesWindow(self)

  File "/usr/lib/python3/dist-packages/quodlibet/qltk/exfalsowindow.py", line 277, in __init__
    super().__init__()

TypeError: __init__() missing 1 required positional argument: 'parent'
```

Test System
-----------

### Which version of Quod Libet?
4.4

### Which operating system 
Kubuntu 20.04

**Comment by declension** [comment]
This should be fixed in d96634d95fda69110722bf14716eacf329d63438

See #3608

**Comment by CreamyCookie** [comment]
@declension Thanks! 

Weird, is it me or is GitHub getting buggier? I remember it searching existing issues when you enter an issue title. (also I searched manually but for some reason that never popped up)

**Comment by MrReSc** [comment]
The problem is still present in the flatpak version 4.4.0 from Flathub.

**Comment by declension** [comment]
Hopefully this is gone fully now in https://github.com/quodlibet/quodlibet/commit/3d5915fee899a3c9c64bf7c3403a9aa29fa31100
